Omega_ai_ai[:,:] +=  +1.00000000  * extract_mat(F, "vo", o, v);
Omega_ai_ai[:,:] +=  -1.00000000  * extract_mat(g_p, "IIvo", o, v);
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  +1.00000000  * np.einsum("A,Aai->ai", extract_mat(h_p, "IV", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  +1.00000000  * np.einsum("jb,aibj->ai", extract_mat(F, "ov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  -1.00000000  * np.einsum("Aab,Abi->ai", extract_mat(g_p, "IVvv", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  +1.00000000  * np.einsum("Aji,Aaj->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  -2.00000000  * np.einsum("Ajj,Aai->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  -1.00000000  * np.einsum("jb,aibj->ai", extract_mat(g_p, "IIov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  -1.00000000  * np.einsum("jikb,ajbk->ai", extract_mat(g, "ooov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  +1.00000000  * np.einsum("jbac,bjci->ai", extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  -2.00000000  * np.einsum("Ajb,Aaibj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
Omega_ai_ai[:,:] = Omega_ai_ai[:,:] .+  +1.00000000  * np.einsum("Ajb,Aajbi->ai", extract_mat(g_p, "IVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
